FROM mmatache/kind_runner:latest as build

ARG  nsm_repo=https://cisco-app-networking.github.io/networkservicemesh.git

RUN  git clone $nsm_repo /go/src/cisco-app-networking.github.io/networkservicemesh

# Add examples code contents
RUN mkdir -p /go/src/github.com/networkservicemesh/examples
COPY examples  /go/src/github.com/networkservicemesh/examples

COPY examples/kubeconfigs/config /go/src/kubeconfigs/config

ENV KUBECONFIG=/go/src/kubeconfigs/config